### ISSUE TITLE
new

### ISSUE THREAD

**Issue by OreoluwaHelen** [jojitoon/ama#1]

**Comment by JojiAndela** [comment]
m, sanlknknlsan

**Comment by JojiAndela** [comment]
const commentsController = {
  addComment: (req, res) => {
    const { articleId, commentId } = req.params;
    const { content } = req.body;
    const userId = req.currentUser.id;

    const userComment = {
      content: escape(content.trim()),
      userId
    };

    if (commentId) {

**Comment by JojiAndela** [comment]
`const commentsController = {
  addComment: (req, res) => {
    const { articleId, commentId } = req.params;
    const { content } = req.body;
    const userId = req.currentUser.id;

    const userComment = {
      content: escape(content.trim()),
      userId
    };

    if (commentId) {`
